### ISSUE TITLE
compile error in openfoam 2.3

### ISSUE THREAD

**Issue by graceyangfan** [ffelis/dev3eulerSprayFoam#1]
FOAM FATAL ERROR: 
previous iteration field
IOobject: volScalarField p_rgh "/root/OpenFOAM/root-2.3.0/run/spraytest/0"

  not stored.  Use field.storePrevIter() at start of iteration.

    From function GeometricField<Type, PatchField, GeoMesh>::prevIter() const
    in file /opt/OpenFOAM-2.3.0/src/OpenFOAM/lnInclude/GeometricField.C at line 828.

FOAM aborting

**Comment by ffelis** [comment]
Hello,
The solver was conceived to be used with version 2.4. Give it a try with that version only.
Best regards.

**Comment by graceyangfan** [comment]
thanks for your replay,it works well in openfoam 2.4.x
