### ISSUE TITLE
Choose Y-Eqn Model with turbdiff

### ISSUE THREAD

**Issue by graceyangfan** [ffelis/dev3eulerSprayFoam#2]
hello，
       Thanks for your sharing,I have learnt a lot from your code.However,I have no idea where these
Y-Eqn comes from,would you offer some relative papers?I did not find them in you Doctoral thesis.

**Comment by ffelis** [comment]
Hi,
You can find these equations in section "2.2.2 Turbulentmass-flux" (page 22) of my doctoral thesis. Then, the equation to solve is Eq. 2.22 (page 16).
Hope this helps.
Cheers.
