### ISSUE TITLE
A small bug in Y-Eqn

### ISSUE THREAD

**Issue by graceyangfan** [ffelis/dev3eulerSprayFoam#3]
- fvm::laplacian
        (
            volScalarField("Dab",
            (rho2/rho)*(Dab + alphatab*turbulence->nut())),
            alpha1
        )
should be：
   - fvm::laplacian
        (
            volScalarField("Dab",
            (Dab + alphatab*turbulence->nut())),
            alpha1
        )
This bug influence the result seriously when the liquid and gas density ratio is very high

**Comment by ffelis** [comment]
Hi, thanks for the revision. However, the equation is correct. The original equation is for \tilde{Y} (the mass fraction), so when you transform everything into the volume fraction \bar{Y} (alpha1 here), there are these extra rho2/rho that appears. In general, you have:

d Ytilde = rho1*rho2/(rho^2)*d Ybar

Cheers.

**Comment by graceyangfan** [comment]
thanks a lot. By the way.when I apply this solver to a jet,I find the results is far away from the experiment,bu when i change the the laplacian compute,the results is good.I test different blend parameter BF as 0,0.5,1.0.
None of them work well,unless I change the laplacian compute.I have no idea where is wrong.
